GET http://localhost:5271/todos

###

POST http://localhost:5271/todos
Content-Type: application/json

{
    "id": 1,
    "name": "Eerste todo",
    "dueDate": "2021-12-31",
    "isCompleted": false
}

###

POST http://localhost:5271/todos
Content-Type: application/json

{
    "id": 2,
    "name": "Snapje",
    "dueDate": "2021-12-31",
    "isCompleted": false
}

###

GET http://localhost:5271/todos/2

###  DELELTE
DELETE http://localhost:5271/todos/2